language: generic
dist: bionic
cache: packages

#addons: 
#  apt: 
#    packages: 
#      - libarchive-dev
#      - singularity-container

install:
  # Check dead links
  - sudo apt-get install -qq singularity-container
  # Check dead links
  - sudo apt-get install -qq npm
  - npm config set strict-ssl false
  - sudo npm install -g markdown-link-check

script:
  # Show the location
  - which singularity
  # Show the singularity version
  - singularity --version
  # Build the container
  - ./build_container
  # Run the container
  - ./lolcow.sif
  # Check dead links
  - rm -f *.sif
  - rm -f *.tar.gz
  - sudo rm -rf singularity
  - ./scripts/check_dead_links || true
